dataset: ./datasets/paper_quditkit/srv_3q_dataset
model_dir: ./models/trained/default_model_srv
hf_repo: null
num_samples: 64
save_output: true
save_folder: ./inference/

model_params:
  guidance_scale: 10.0
  sample_steps: 20
  auto_batch_size: 512

wandb:
  enable: true
  project: qcircuit-generation
  run_name: test_run