general:
  output_path: ./models/trained/
  model_name: cloob_model
  experiment_name: cloob_model_training
  dataset: ./datasets/qc_srv_dataset_3to8qubit/
  njobs: 16
  device: auto
  resume: false
  verbose: true

model:
  type: QC_Cond_UNet
  save_type: pt

  params:
    model_features: [128, 128, 256]
    clr_dim: 4
    num_clrs: 4
    t_emb_size: 256
    cond_emb_size: 512
    num_heads: [8, 8, 2]
    num_res_blocks: [2, 2, 4]
    transformer_depths: [1, 2, 1]

training:
  learning_rate: 3e-4
  optimizer: Adam
  loss: MSELoss
  num_epochs: 75
  batch_size: 256 
  enable_guidance_train: true
  guidance_train_p: 0.1
  cached_text_enc: true
  output_path: ./models/trained/
  model_name: cloob_model
  experiment_name: cloob_model_training
  ckpt_path: ./cp_saves/
  ckpt_interval: 3
  wandb:
    enable: true
    project: qcircuit-generation
    run_name: cloob_model_training
  one_cycle:
    enable: true
    max_lr: 3e-4
    pct_start: 0.1
    anneal_strategy: cos
    div_factor: 25.0
    final_div_factor: 10000.0

staged_training:
  enable: true
  stage1:
    num_epochs: 60
    batch_size: 256
    bucket_batch_size: -1
  stage2:
    num_epochs: 15
    batch_size: 1
    bucket_batch_size: 256

text_encoder:
  type: CachedFrozenOpenCLIPEmbedder
  params:
    arch: RN50
    version: null
    max_length: 23
    freeze: true
    layer: penultimate
    enable_cache_token_limit: true
    local_weights_path: "./models/encoders/clip_rn50_yfcc_epoch_28.pt"

scheduler:
  type: DDIMScheduler
  params:
    num_train_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: cos_alpha
    input_perturbation: 0.1
    prediction_type: epsilon
    eta: 1
