# Stage-2 curriculum finetuning for unitary compilation.

general:
  output_path: ./artifacts/models/unitary-curriculum-learning/
  model_name: unitary_curriculum_stage2
  experiment_name: unitary_curriculum_stage2
  init_from_pipeline_dir: ./artifacts/models/unitary-curriculum-learning/unitary_curriculum_stage1
  dataset: ./artifacts/datasets/unitary-curriculum-learning/stage2
  njobs: 8
  device: auto
  verbose: true

model:
  type: QC_Compilation_UNet
  save_type: pt
  params:
    model_features: [128, 128, 256]
    clr_dim: 8
    num_clrs: 8
    t_emb_size: 256
    cond_emb_size: 512
    num_heads: [8, 8, 2]
    num_res_blocks: [2, 2, 4]
    transformer_depths: [1, 2, 1]
    unitary_encoder_config:
      cond_emb_size: 512
      model_features: [2, 32, 64, 512]
      num_heads: 8
      transformer_depths: [2, 2]
      dropout: 0.2

training:
  learning_rate: 5e-5
  optimizer: Adam
  lr_scheduler: OneCycleLR
  loss: MSELoss
  num_epochs: 50
  batch_size: 256
  enable_guidance_train: true
  guidance_train_p: 0.1
  max_grad_norm: 1.0
  cached_text_enc: true
  ckpt_path: ./artifacts/models/checkpoints/unitary_curriculum_stage2/
  ckpt_interval: 5
  wandb:
    enable: true
    project: qcircuit-generation
    run_name: unitary_curriculum_stage2

text_encoder:
  type: CachedFrozenOpenCLIPEmbedder
  params:
    arch: ViT-B-32
    version: null
    max_length: 77
    freeze: true
    layer: penultimate
    enable_cache_token_limit: true
    local_weights_path: "./artifacts/models/encoders/open_clip_ViT-B-32_laion2b_s34b_b79k.bin"

scheduler:
  type: DDIMScheduler
  params:
    num_train_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: cos_alpha
    input_perturbation: 0.1
    prediction_type: epsilon
    eta: 1
